# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/oneplus/ossi/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),ossi)

$(call add-radio-file-sha1-checked,radio/abl.img,3db529887f50197e0b6ccd2900b90f0ba5aed6c9)
$(call add-radio-file-sha1-checked,radio/bluetooth.img,7bacb36581258afc374a99d641e96b9ce751d506)
$(call add-radio-file-sha1-checked,radio/core_nhlos.img,fd38f6f8c19cda02cf553a01074441a5a5d133b7)
$(call add-radio-file-sha1-checked,radio/devcfg.img,709bfc33892eb9405f37f04682bb7f8c134ef078)
$(call add-radio-file-sha1-checked,radio/dsp.img,9606e98a9e1a1b886170e4858e7dc5ab2910548a)
$(call add-radio-file-sha1-checked,radio/engineering_cdt.img,13f5f33df779408b04cdfb3d78dd1ebbd3afb7b4)
$(call add-radio-file-sha1-checked,radio/featenabler.img,b0c21c9e046a2300e8ea581b137418d1dbba2a0d)
$(call add-radio-file-sha1-checked,radio/hyp.img,1fccfd387a1beeff3f990bf81f1a41c595783911)
$(call add-radio-file-sha1-checked,radio/imagefv.img,2f045c685b252db53a5328f9eeafd723734007f9)
$(call add-radio-file-sha1-checked,radio/keymaster.img,9e0c38a01148c94261c26c88ddadce16abacaf6a)
$(call add-radio-file-sha1-checked,radio/mmodem.img,9648ef912bd5e938790266b27a9b7bbccad42c9f)
$(call add-radio-file-sha1-checked,radio/oplus_sec.img,611818027635a560cf56f608943533a9560a7c50)
$(call add-radio-file-sha1-checked,radio/oplusstanvbk.img,967704727c162dc5cd801aa2630c93a56232f8d8)
$(call add-radio-file-sha1-checked,radio/qupfw.img,2474571a8bb4ba919ba6a807bbf50ccd3cde93e2)
$(call add-radio-file-sha1-checked,radio/rpm.img,b65ca23ef867c3999f186395a7b5317ffc70d10b)
$(call add-radio-file-sha1-checked,radio/splash.img,cef1d4886175660f305e78ab39b7782f8625e431)
$(call add-radio-file-sha1-checked,radio/tz.img,74b38587ce1d05358f4c8d9e8926d11e89288386)
$(call add-radio-file-sha1-checked,radio/uefisecapp.img,d6289aef92664932df6474444182fb49edacf52b)
$(call add-radio-file-sha1-checked,radio/xbl.imgbed846128c4c336d5349e0446347ccae31afc491)
$(call add-radio-file-sha1-checked,radio/xbl_config.img,33916d0a243f80f4b285c0d60185322f52e07d83)

endif
